CREATE TABLE ticker (
    id INT NOT NULL AUTO INCREMENT,
    last DECIMAL(15, 4) NOT NULL,
    high DECIMAL(15, 4) NOT NULL,
    low DECIMAL(15, 4) NOT NULL,
    vwap DECIMAL(15, 4) NOT NULL,
    volume DECIMAL(20, 8) NOT NULL,
    bid DECIMAL(15, 4) NOT NULL,
    ask DECIMAL(15, 4) NOT NULL,
    timestamp INT NOT NULL,
    open DECIMAL(15, 4) NOT NULL,
    CONSTRAINT pk_id PRIMARY KEY (id)
)